import Head from "next/head";
import { Inter } from "next/font/google";
import RadarComponent from "@/components/radar";
import StatementComponent from "@/components/statement";
import MailComponent from "@/components/mail";
import { datas, _categories } from "@/helper/database";
import { useState, useReducer } from "react";
import { reducerFunctions, initialReducers } from "@/helper/reducer";
import RadarContainer from "@/components/radarcontainer";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [result, setResult] = useState<boolean>(false);
  const [mail, setMail] = useState<string>("");
  const [tasks, dispatch] = useReducer(reducerFunctions, initialReducers);
  const [resultArray, setResultArray] = useState<
    {
      categories: _categories;
      value: number;
    }[]
  >([]);

  const resultHandler = () => {
    resultArray.map((res) => {
      if (res) {
        dispatch({ type: res.categories, payload: res.value });
      }
      setResult(!result);
    });
  };
  const submitHandler = (e: string) => {
    setMail(e);
  };
  console.log(tasks);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        {result ? (
          <RadarContainer tasks={tasks} />
        ) : mail ? (
          <>
            <h1 className="header">Agile Survey</h1>
            {/* <div className="radarsize">
          <RadarComponent />
        </div> */}
            {datas.map((data, i) => (
              <StatementComponent
                key={data.id}
                statement={data.statement}
                setResultArray={setResultArray}
                indexArray={i}
                resultArray={resultArray}
                categories={data.categories}
                dispatch={dispatch}
                tasks={tasks}
              />
            ))}
            <button onClick={resultHandler} className="button right">
              Result &rArr;
            </button>
          </>
        ) : (
          <MailComponent setMail={submitHandler} dispatch={dispatch} />
        )}
      </main>
    </>
  );
}
